### PR TITLE
Gradle and SonarQube 4.5 support

### PR DESCRIPTION
**Pull request by zippy1978**
- Added Gradle project detection
- Made plugin compliant with SonarQube 4.5
- Moved SQALE model to resources
- Formatted code

### CODE REVIEW

**Comment by benzonico** [comment]
Hi, 

Thanks for your contribution. 
We will have a look at it during next Android sprint taht should happen within the next month or so.

Some remarks about your PR : 

You have only one commit concerning several subjects : it is hard from a plugin maintainer point of view to actually integrate your contribution. 
Please make, at the very least, one commit per topic and even better, one pull request by subject, which will allow us to be able to pick the contribution that are worthy (and make feedback, review on each more easily).

Thanks again.

**Comment by zippy1978** [comment]
Hi,

Ok : do you want me to issue different PR for those features ?

**Comment by benzonico** [comment]
If it is not too much work for you, yes please.

**Comment by benzonico** [comment]
Upgrade to SonarQube LTS has been made. Support of gradle is not relevant anymore due to : http://jira.codehaus.org/browse/SONARANDRO-30 
Therefore I am closing this pull request.

**Comment by zippy1978** [comment]
Nice :)

**Pull request closed without merging**
